# ------------------------------------------------------------------------------
# Pull base image
FROM alpine:latest
LABEL author="Brett Kuskie <fullaxx@gmail.com>"

# ------------------------------------------------------------------------------
# Set environment variables
ENV TZ=Etc/Zulu

# ------------------------------------------------------------------------------
# Create a docker image suitable for development
RUN apk update && \
    apk add --no-cache bash bind-tools curl iproute2-ss iptables iputils-ping mtr nano openvpn python3 && \
    rm -rf /var/cache/apk/*

# ------------------------------------------------------------------------------
# Prepare the image
COPY app.sh roundrobin.py connect.sh cycle.sh up.sh down.sh debug.sh /app/

# ------------------------------------------------------------------------------
# Add volumes
VOLUME /profiles

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/app.sh"]
