# ------------------------------------------------------------------------------
# Pull base image
FROM ubuntu:noble
LABEL author="Brett Kuskie <fullaxx@gmail.com>"

# ------------------------------------------------------------------------------
# Set environment variables
ENV TZ=Etc/Zulu
ENV DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------------------------
# Create a docker image suitable for development
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
      coreutils \
      curl \
      dnsutils \
      iproute2 \
      iptables \
      iputils-ping \
      mtr \
      nano \
      openvpn \
      python3-minimal && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Prepare the image
COPY app.sh roundrobin.py connect.sh cycle.sh up.sh down.sh debug.sh /app/

# ------------------------------------------------------------------------------
# Add volumes
VOLUME /profiles

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/app.sh"]
